version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: evolux-challenge-app
    volumes:
      - .:/home/flask/app
    ports:
      - 5000
    environment:
      - SQLALCHEMY_DATABASE_URI=postgres://postgres:postgres@db:5432/evolux_challenge
      - JWT_SECRET_KEY=mysupersecretkey
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    container_name: evolux-challenge-db
    tty: true
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=evolux_challenge
    volumes:
      - ./.pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx:1.19.2-alpine
    container_name: evolux-challenge-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 5000:5000
    depends_on:
      - app
