version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: evolux-challenge-app
    command: sleep infinity
    volumes:
      - .:/home/flask/app
    ports:
      - 5000:5000
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    container_name: evolux-challenge-db
    tty: true
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=evolux_challenge
    volumes:
      - ./.pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: evolux-challenge-pgadmin
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=123
    volumes:
      - ./.pgadmin:/var/lib/pgadmin
    ports:
      - 9009:80
