"""empty message

Revision ID: 270f385e5000
Revises: b3bc3c6fb750
Create Date: 2020-08-26 14:22:07.393177

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '270f385e5000'
down_revision = 'b3bc3c6fb750'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dids',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('value', sa.String(length=20), nullable=False),
    sa.Column('monthy_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('setup_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dids')
    # ### end Alembic commands ###
